### ISSUE TITLE
sdk/traffic_manager/azuretrafficmanager

### ISSUE THREAD

**Issue by hrodz13** [Azure-Refactor/circuit-oneops-1#13]
Integrate azure_mgmt_traffic_manager gem version 0.8.0 into the azuretrafficmanager cookbook and remove the rest-client calls.

**Comment by samawia-moin-confiz** [comment]
Hi @hrodz13 

Currently azure traffic manager is using rest-client calls because azure sdk didn't provide any support for traffic manager. 
azuretrafficmanager is not a part of network sdk.
Azure SDK now supports traffic manager as a separate gem `azure_mgmt_traffic_manager`. We need to migrate azuretrafficmanager cookbook to the latest gem using `azure_mgmt_traffic_manager`.

**Comment by hrodz13** [comment]
Oh good call! I believe this is the same case as the dns sdk, correct? I'll change the issue name

**Comment by samawia-moin-confiz** [comment]
As azuretrafficmanager cookbook is using Rest-client for API calls, so we are not taking up on this for now, we will update this cookbook in Phase 2  ( Update to Fog-azurerm).
